### ISSUE TITLE
Feature: Allow Setting Alternative Hostname or IP Address for Target Application

### ISSUE THREAD

**Issue by chernobog** [ravesheep/ProtonVPN-windows#2]
Please allow setting an alternative hostname or IP address for targeting the application being updated with the new port number. References to localhost or 127.0.0.1 do not work in my network, and I need to specify the private IP address of my host for other applications to interact with qBittorrent.

**Comment by ravesheep** [comment]
Thank you for reporting this, you can now set both the IP address and port in the settings.

Added in [v3.2.10.1](https://github.com/ravesheep/ProtonVPN-windows/releases/tag/3.2.10.1).
