### ISSUE TITLE
How does this app work ? 

### ISSUE THREAD

**Issue by Its-Ankush** [ravesheep/ProtonVPN-windows#5]
Hey team, I installed the app, ive added ProtonVPN and qbittorrent to PATH but now everytime I run the command ```ProtonVPN.Launcher --PortForwardingApp qBittorrent``` only the protonVPN application launches as usual but i dont see the port in qbittorrent GUI being updated ? Even if I change the server, the port is never updated ? Am I mistaken ? Does this app automatically update the port used for incoming connections in qbittorrent or am I missing something ?

**Comment by Its-Ankush** [comment]
Edit - Sorry about this, just got my answers from here - 

![Capture](https://github.com/ravesheep/ProtonVPN-windows/assets/68053631/6013c1dd-ea31-43a6-8e7d-6b93eea56feb)

**Comment by Its-Ankush** [comment]
cxvgbxcvb

**Comment by ravesheep** [comment]
## Clearing things up for others who might have this question

While this works, it seems that people are confused about the Web UI.  
qBittorrent's Web UI is disabled by default, and can be enabled and configured in its options (see below).  
You should then use the same settings in ProtonVPN to allow it to use qBittorrent's Web UI.

![image](https://github.com/ravesheep/ProtonVPN-windows/assets/147330391/d91702b8-fe59-49dc-a0aa-f9a143028179)

If "Bypass authentication" is enabled, the default settings should work:
![image](https://github.com/ravesheep/ProtonVPN-windows/assets/147330391/62bbe93c-9196-4093-a159-c0aaa6bd4499)

If **NOT** using the "Bypass authentication" option, make sure to add the username and password in ProtonVPN:
![image](https://github.com/ravesheep/ProtonVPN-windows/assets/147330391/b0ddfe0e-0382-463c-bd44-deac392dcf4d)

Selecting "Command Line" restarts qBittorrent with `qBittorrent --torrenting-port=...`, which just works without changing any option. Might be less confusing for some users.
