### ISSUE TITLE
Few cli commands doesn't seem to be working 

### ISSUE THREAD

**Issue by sid1552** [ravesheep/ProtonVPN-windows#6]
ProtonVPN.Launcher --Connect  ✅

ProtonVPN.Launcher --Connect server US-FL#53  ✅

The above commands seem to be working but the ones below are not working, am I doing something wrong?

ProtonVPN.Launcher --Connect US Dallas  ❌
This is not working

**Comment by ravesheep** [comment]
Thank you for reporting this.  
This was a mistake in the readme which [is now fixed](https://github.com/ravesheep/ProtonVPN-windows/commit/64cf82361481bf02b6d4685670f00d1a014ee156)!  

You need to add `server` like this:  
`ProtonVPN.Launcher --Connect server US Dallas`

**Comment by sid1552** [comment]
@ravesheep  Thank you
