### ISSUE TITLE
How to use citynames which has space in between

### ISSUE THREAD

**Issue by sid1552** [ravesheep/ProtonVPN-windows#7]
I am using this command -->

ProtonVPN.Launcher --Connect server US New York

It doesnt seem to be working . Same for cities which has space in between like los angeles ,san jose etc

**Comment by sid1552** [comment]
Whats the correct syntax for these cities

**Comment by ravesheep** [comment]
Same syntax, you're just using the command line wrong.  
Arguments that contain spaces should be wrapped in double quotes.

**Comment by sid1552** [comment]
@ravesheep 
Thanks for replying. Actually, i am using this command 

import subprocess
import os

# Set the directory where the command will be executed
directory = r"C:\Program Files\Proton\VPN"
os.chdir(directory)

# Command to be executed
command = "ProtonVPN.Launcher --Connect server US Dallas"

# Execute the command
subprocess.run(command, shell=True)



The above seems to be working , but when i use something like this 


import subprocess
import os

# Set the directory where the command will be executed
directory = r"C:\Program Files\Proton\VPN"
os.chdir(directory)

# Command to be executed
command = "ProtonVPN.Launcher --Connect server US New York"

# Execute the command
subprocess.run(command, shell=True)





it doesn't seem to work. Same with cities with spaces

**Comment by sid1552** [comment]
@ravesheep 
thanks
